// <auto-generated />
using System;
using HeuteApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeuteApp.Infrastructure.Migrations
{
    [DbContext(typeof(HeuteDbContext))]
    [Migration("20260312220553_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Board.BoardCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("board_cards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Board.HeuteBoardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("OwnerId", "Date")
                        .IsUnique();

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.LayoutSectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId", "Name")
                        .IsUnique();

                    b.ToTable("layout_sections", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Board.BoardCardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Board.HeuteBoardModel", "Board")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Board.BoardCardContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("BoardCardModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Content_Title");

                            b1.HasKey("BoardCardModelId");

                            b1.ToTable("board_cards");

                            b1.WithOwner()
                                .HasForeignKey("BoardCardModelId");
                        });

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Board.BoardCardPlacement", "Placement", b1 =>
                        {
                            b1.Property<Guid>("BoardCardModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_ColIndex");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_ColSpan");

                            b1.Property<int>("RowIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_RowIndex");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_RowSpan");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Placement_SectionName");

                            b1.HasKey("BoardCardModelId");

                            b1.ToTable("board_cards");

                            b1.WithOwner()
                                .HasForeignKey("BoardCardModelId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Placement");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Board.HeuteBoardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Layout");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridDimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("HeuteLayoutModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColCount")
                                .HasColumnType("integer")
                                .HasColumnName("Dimensions_ColCount");

                            b1.Property<int>("RowCount")
                                .HasColumnType("integer")
                                .HasColumnName("Dimensions_RowCount");

                            b1.HasKey("HeuteLayoutModelId");

                            b1.ToTable("layouts");

                            b1.WithOwner()
                                .HasForeignKey("HeuteLayoutModelId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.LayoutSectionModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", "Layout")
                        .WithMany("Sections")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridRect", "Position", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Position_ColIndex");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Position_ColSpan");

                            b1.Property<int>("RowIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Position_RowIndex");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Position_RowSpan");

                            b1.HasKey("LayoutSectionModelId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionModelId");
                        });

                    b.Navigation("Layout");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Board.HeuteBoardModel", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
