// <auto-generated />
using System;
using HeuteApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeuteApp.Infrastructure.Migrations
{
    [DbContext(typeof(HeuteDbContext))]
    [Migration("20260228120644_InitialCreate10")]
    partial class InitialCreate10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Aggregates.HeuteBoardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Aggregates.HeuteLayoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Entities.BoardCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("board_cards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Entities.LayoutSectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("layout_sections", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Aggregates.HeuteBoardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Aggregates.HeuteLayoutModel", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Entities.BoardCardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Aggregates.HeuteBoardModel", "Board")
                        .WithMany("m_cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridRect", "Position", b1 =>
                        {
                            b1.Property<Guid>("BoardCardModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Col")
                                .HasColumnType("integer")
                                .HasColumnName("position_col");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer")
                                .HasColumnName("position_colSpan");

                            b1.Property<int>("Row")
                                .HasColumnType("integer")
                                .HasColumnName("position_row");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer")
                                .HasColumnName("position_rowSpan");

                            b1.HasKey("BoardCardModelId");

                            b1.ToTable("board_cards");

                            b1.WithOwner()
                                .HasForeignKey("BoardCardModelId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Entities.LayoutSectionModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Aggregates.HeuteLayoutModel", "Layout")
                        .WithMany("m_sections")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridSize", "Size", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColCount")
                                .HasColumnType("integer")
                                .HasColumnName("size_colCount");

                            b1.Property<int>("RowCount")
                                .HasColumnType("integer")
                                .HasColumnName("size_rowCount");

                            b1.HasKey("LayoutSectionModelId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionModelId");
                        });

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Rect", "Rect", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("rect_height");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("rect_width");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("rect_x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("rect_y");

                            b1.HasKey("LayoutSectionModelId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionModelId");
                        });

                    b.Navigation("Layout");

                    b.Navigation("Rect")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Aggregates.HeuteBoardModel", b =>
                {
                    b.Navigation("m_cards");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Aggregates.HeuteLayoutModel", b =>
                {
                    b.Navigation("m_sections");
                });
#pragma warning restore 612, 618
        }
    }
}
