// <auto-generated />
using System;
using HeuteApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeuteApp.Infrastructure.Migrations
{
    [DbContext(typeof(HeuteDbContext))]
    [Migration("20260226064100_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("board_cards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.LayoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.LayoutSectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("layout_sections", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardCardEntity", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", "Board")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridRect", "Position", b1 =>
                        {
                            b1.Property<Guid>("BoardCardEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Col")
                                .HasColumnType("integer");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer");

                            b1.HasKey("BoardCardEntityId");

                            b1.ToTable("board_cards");

                            b1.WithOwner()
                                .HasForeignKey("BoardCardEntityId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Persistence.Entities.LayoutEntity", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.LayoutSectionEntity", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Persistence.Entities.LayoutEntity", "Layout")
                        .WithMany("Sections")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridSize", "Size", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColCount")
                                .HasColumnType("integer");

                            b1.Property<int>("RowCount")
                                .HasColumnType("integer");

                            b1.HasKey("LayoutSectionEntityId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionEntityId");
                        });

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Rect", "Rect", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("LayoutSectionEntityId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionEntityId");
                        });

                    b.Navigation("Layout");

                    b.Navigation("Rect")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.LayoutEntity", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
