// <auto-generated />
using System;
using HeuteApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeuteApp.Infrastructure.Migrations
{
    [DbContext(typeof(HeuteDbContext))]
    [Migration("20260330232250_InitialCreate9")]
    partial class InitialCreate9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Dailyboard.DailyboardCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyboardId");

                    b.ToTable("dailyboard_cards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Dailyboard.HeuteDailyboardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("dailyboards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.LayoutSectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId", "Name")
                        .IsUnique();

                    b.ToTable("layout_sections", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Dailyboard.DailyboardCardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Dailyboard.HeuteDailyboardModel", "Dailyboard")
                        .WithMany("Cards")
                        .HasForeignKey("DailyboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Dailyboard.DailyboardCardContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("DailyboardCardModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Content_Title");

                            b1.HasKey("DailyboardCardModelId");

                            b1.ToTable("dailyboard_cards");

                            b1.WithOwner()
                                .HasForeignKey("DailyboardCardModelId");
                        });

                    b.OwnsOne("HeuteApp.Core.ValueObjects.Dailyboard.DailyboardCardPlacement", "Placement", b1 =>
                        {
                            b1.Property<Guid>("DailyboardCardModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_ColIndex");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_ColSpan");

                            b1.Property<int>("RowIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_RowIndex");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Placement_RowSpan");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Placement_SectionName");

                            b1.HasKey("DailyboardCardModelId");

                            b1.ToTable("dailyboard_cards");

                            b1.WithOwner()
                                .HasForeignKey("DailyboardCardModelId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Dailyboard");

                    b.Navigation("Placement");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Dailyboard.HeuteDailyboardModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Category.HeuteCategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Layout");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Profile.HeuteProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridDimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("HeuteLayoutModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColCount")
                                .HasColumnType("integer")
                                .HasColumnName("Dimensions_ColCount");

                            b1.Property<int>("RowCount")
                                .HasColumnType("integer")
                                .HasColumnName("Dimensions_RowCount");

                            b1.HasKey("HeuteLayoutModelId");

                            b1.ToTable("layouts");

                            b1.WithOwner()
                                .HasForeignKey("HeuteLayoutModelId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.LayoutSectionModel", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", "Layout")
                        .WithMany("Sections")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridRect", "Position", b1 =>
                        {
                            b1.Property<Guid>("LayoutSectionModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Position_ColIndex");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Position_ColSpan");

                            b1.Property<int>("RowIndex")
                                .HasColumnType("integer")
                                .HasColumnName("Position_RowIndex");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer")
                                .HasColumnName("Position_RowSpan");

                            b1.HasKey("LayoutSectionModelId");

                            b1.ToTable("layout_sections");

                            b1.WithOwner()
                                .HasForeignKey("LayoutSectionModelId");
                        });

                    b.Navigation("Layout");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Dailyboard.HeuteDailyboardModel", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Models.Layout.HeuteLayoutModel", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
