// <auto-generated />
using System;
using HeuteApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeuteApp.Infrastructure.Migrations
{
    [DbContext(typeof(HeuteDbContext))]
    partial class HeuteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("board_cards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardCardEntity", b =>
                {
                    b.HasOne("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", "Board")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeuteApp.Core.ValueObjects.GridRect", "Position", b1 =>
                        {
                            b1.Property<Guid>("BoardCardEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Col")
                                .HasColumnType("integer");

                            b1.Property<int>("ColSpan")
                                .HasColumnType("integer");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.Property<int>("RowSpan")
                                .HasColumnType("integer");

                            b1.HasKey("BoardCardEntityId");

                            b1.ToTable("board_cards");

                            b1.WithOwner()
                                .HasForeignKey("BoardCardEntityId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HeuteApp.Infrastructure.Persistence.Entities.BoardEntity", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
